### ISSUE TITLE
Proximity sensor bug (?)

### ISSUE THREAD

**Issue by rosenpin** [rosenpin/always-on-amoled#2373]
https://plus.google.com/112055552337422207600/posts/8j86sx92Fbc

**Comment by Mnkyman11** [comment]
I can reproduce it easily, really pissing me off.... no matter what i do, if i put my finger over the proximity sensor it goes off for a split second, wakes the device, returns to AOD, then goes off again in a constant cycle... this happens weather or not the option for Pocket detection is enabled or not....

**Comment by Y2K-x** [comment]
Can also confirm reproducibility on the latest "retail" version, with the Sprint Galaxy S6 (SM-G920P). No amount of settings combinations fixes it for me.

**Comment by rosenpin** [comment]
This was fixed recently
