### ISSUE TITLE
Locked out of Your Phone

### ISSUE THREAD

**Issue by rosie8715** [rosenpin/always-on-amoled#2376]
I am currencly using a Samsung Galaxy S7 on Sprint.  My software version is G930PVPS4BQG1, my hardware version is REv0.6. My model number is Sm-G930P. I am running Android 7.0. My Baseband Version is G930Pvps4bqg1. The issue is that when the  app is being used, it can lock you out of your phone even if the back button is supposed to take you back to your lock screen. There are two ways you can bypass the bug. The first is to let the phone die which can take days. Thee second is to start to press random button and hope that the phone lets you in. The issue is made worse because it overrides the force shutdown function that Samsung programed into the phone. This issue forced me to have to delete the app out of fear that it might happen again.

**Comment by rosenpin** [comment]
Thanks for letting me know.
I will look into it and try to fix it ASAP.
Just FYI, you can force reboot your phone by pressing the power button for about 30 seconds.

**Comment by rosenpin** [comment]
The app should not allow the user to disable all the options that allow you to unlock, simulated home button, double tap to wake etc..

**Comment by rosenpin** [comment]
Duplicate
