### ISSUE TITLE
Always On Display Amoled Proximity Sensor

### ISSUE THREAD

**Issue by Catarinaf58** [rosenpin/always-on-amoled#2380]
Hi! I bought your app today, its really useful, thanks for all your work!
I've been using your app for some hours, and im facing an issue with it.
I have a Samsung Galaxy A3 2016 phone with android 7.0. 
I activated the proximity sensor option, and sometimes is works just fine, though some other times, when I cover my phone's sensor, the clock doesnt appear anymore and i have to unlock and lock my phone again for it to show. Is it an app bug or a problem with my proximity sensor?

Thanks!

**Comment by Catarinaf58** [comment]
Update: i tested my proximity sensor using the samsung *#0*# and its working fine, so i guess its an app bug...

**Comment by rosenpin** [comment]
Probably Related to https://github.com/rosenpin/always-on-amoled/issues/2373
