### ISSUE TITLE
Automation Tasks Fail Every Time

### ISSUE THREAD

**Issue by Mnkyman11** [rosenpin/always-on-amoled#2382]
Trying to use Macrodroid to start or stop the service (apps built in tasker integration) causes nothing to happen and a notification containing "Error: The service wasn't initialized correctly" to be displayed
_**Device is Galaxy S6 (SM-G920V) running Android 7.0 btw**_

**Comment by ldittmar81** [comment]
Yes. I got this problem too. I can start with tasker, but I cant stop it. "Error: The service wasn't initialized correctly" - MainService.initialized seens to be always false -
 https://github.com/rosenpin/AlwaysOnDisplayAmoled/blob/99b43c2b2faca2da235d1139d3bf4f5042daa8e6/app/src/main/java/com/tomer/alwayson/tasker/FireReceiver.java#L28

**Comment by rosenpin** [comment]
I believe this was fixed a long time ago, if I'm wrong hopefully someone will comment on this issue
