### ISSUE TITLE
AOD turns the screen on after shut down 

### ISSUE THREAD

**Issue by sysqo82** [rosenpin/always-on-amoled#2384]
When setting the shut down timer, the AOD functionality shuts down but in doing so, it turns the screen on thus making the service to be turned on again. This is very annoying, especially when setting the timer to 1 minute.
It's installed on a oneplus 3 running OOS 4.1.7 bated on Android 7.1.1

**Comment by cziberez** [comment]
Agree. I have a smart cover and AOD works only when it's open. But if I shut down the cover the screen turns on.

**Comment by rosenpin** [comment]
This was fixed long ago
