### ISSUE TITLE
[Suggestion] Turn off Music Player notification (like Spotify) when Music control is on

### ISSUE THREAD

**Issue by cziberez** [rosenpin/always-on-amoled#2385]
![screenshot_2017-10-01-15-00-16-890_lockscreen](https://user-images.githubusercontent.com/18663813/31054714-66395878-a6b9-11e7-9f13-52b16e0fbf07.png)

Sometimes it's just annoying and doesn't refresh only if I pause and restart the song.

**Comment by lmore377** [comment]
I agree. It's quite annoying indeed

**Comment by rosenpin** [comment]
you can disable it inside the app under the customize watchface section

**Comment by rosenpin** [comment]
you can disable it inside the app under the customize watchface section

**Comment by rosenpin** [comment]
This is still an issue, related to https://github.com/rosenpin/always-on-amoled/issues/2413
