### ISSUE TITLE
Music controls next/prev buttons issue with AntennaPod

### ISSUE THREAD

**Issue by jsteel44** [rosenpin/always-on-amoled#2391]
AntennaPod (F-Droid or Google Play) has an option to have the next/prev buttons skip forward/backward so many seconds rather than skip to the next/prev track. With your music controls, It seems to skip a track AND jump ahead so many seconds with one press. The native Android lock screen music controls obey the AntennaPod setting and only skip seconds, not next track. Could you take a look at this and match the behaviour of the stock lock screen controls? Thanks

**Comment by rosenpin** [comment]
Pressing the next/prev button on the always on display should skip songs
What device are you using?

**Comment by jsteel44** [comment]
Yes, but not when you set AntennaPod to change that behaviour. I have a Samsung Galaxy A5. Not only do the stock lock screen music controls obey the setting, the stock "always on display" does too. Yours does skip forward the specified number of seconds, but it skips the track first and then jumps forward. I like the look of your version over the stock one as yours has more options, but this issue is a bit of a killer for me. Thanks

**Comment by rosenpin** [comment]
I'll look into it

**Comment by rosenpin** [comment]
As I won't implement custom action for different apps, this issue will be closed
