### ISSUE TITLE
Watch screen not shown when locked (display is dimmed, unlock pattern shown instead)

### ISSUE THREAD

**Issue by OllyFunkster** [rosenpin/always-on-amoled#2398]
Samsung Galaxy S4 Mini running AOKP Oreo Nightly 2018-09-09.

Having set up both lock screen and Always On AMOLED the same as on my S3 mini (LineageOS 14.1), I found that on Oreo when I press the power button to lock the screen, after a delay the unlock pattern is shown instead of the Always On AMOLED watch screen. The display is dimmed and the pocket-mode proximity sensor is working, but the content shown is wrong.

If I enter the unlock pattern, the watch screen is shown for a fraction of a second before the home screen is displayed. Almost like the watch screen was underneath the lock screen instead of on top of it?

**Comment by Goliath0** [comment]
This is the same as me. Described in Issue  LineageOS 16.

**Comment by rosenpin** [comment]
Closing this due to the app having many changes and fixes since. If this issue persist let me know
