### ISSUE TITLE
Cannot use Faceunlock

### ISSUE THREAD

**Issue by AlexOnFOSS** [rosenpin/always-on-amoled#2436]
Hello,

when using the alwayson on Android 9 (Android One) with Xiami Mi3 i cannot use faceunlock
I had to uninstall the app to be able to reuse faceunlock again.
My phone is not rooted.

**Comment by rosenpin** [comment]
Since the lockscreen is active while the aod is active it is to be expected. The face unlock must fail due to a timeout.

Sadly, I don't think there's something I can do to fix it in the app, but I'll look into it

**Comment by rosenpin** [comment]
Closing this due to the app having many changes and fixes since. If this issue persist let me know
