### ISSUE TITLE
Power Button not leaving AOD

### ISSUE THREAD

**Issue by Metalphreek** [rosenpin/always-on-amoled#2441]
Hi there!

When this AOD is activated (with default settings), showing and I press the power-button on the side of the Phone the screen turns black for about a second and then showing the AOD again. The only way to unlock is to double-tap the screen. Luckily this is enabled by default, otherwise I would've been locked out of my phone.

In my opinion it should be the default behavior to leave the AOD when pressing the power button, or is this a bug and should normally work?

I'm using a Huawei Mate 20 Pro with Android 10 and disabled the default AOD.

I really hope that there is a fix for this, because normally I always use the power button to leave the AOD.

**Comment by rosenpin** [comment]
This can't be fixed. Android does not allow registering power button listener
