### ISSUE TITLE
Most Clock- and Date-Designs not transparent

### ISSUE THREAD

**Issue by Metalphreek** [rosenpin/always-on-amoled#2442]
It's me again with another bug.

When I select a background and a clock- and/or date-design (even the accu), it looks like most images doesn't have transparency which leads in a black rectangular background around the element making it look like a mess.
![Screenshot_20200226_180258_com android keyguard](https://user-images.githubusercontent.com/18738153/75368609-4c95b200-58c2-11ea-8b20-a8f5be4714eb.jpg)

**Comment by israelreyesxd** [comment]
![Screenshot_20200327-040138_Clock style](https://user-images.githubusercontent.com/62743857/77744873-eb0b5500-6fdf-11ea-8826-8eb92b53ce37.jpg)

**Comment by rosenpin** [comment]
Thanks! seems really weird, I'll look into it asap

**Comment by rosenpin** [comment]
what device and android version are you using?

**Comment by rosenpin** [comment]
Fixed it, it should be available to download in the next version
