### ISSUE TITLE
Not showing for most of the time

### ISSUE THREAD

**Issue by Metalphreek** [rosenpin/always-on-amoled#2443]
I got a feeling that aod-apps don't work very well with either my Huawei Mate 20 Pro or without a rooted device, because I had this problem with another non-default-aod too:

In most cases this AOD won't show when I lock the screen. Turning off the original AOD or battery saving options didn't change anything for example. I have to go inside the app to re-enable it for at least one time (and then it won't working again)

Are there some settings which we have to adjust on Android 10 to make this app working better? If yes it would be great to list these in the README.md or do I really need a rooted device?

Thanks.

**Comment by rosenpin** [comment]
Can you try with the latest version?  
Also, you should read the Help section of the app or visit https://dontkillmyapp.com/huawei for more information on how to keep the app alive

**Comment by rosenpin** [comment]
Closing this due to the app having many changes and fixes since. If this issue persist let me know
