### ISSUE TITLE
Some text on the page has not been translated

### ISSUE THREAD

**Issue by sjl872964789** [rosenpin/always-on-amoled#2475]
**Describe the bug**
Some text on the page has not been translated

**Context**
 - Device: [Galaxy A6s]
 - OS version: [Android 7.1.2]
 - App version: [1.6.2]

**How to reproduce**
Steps to reproduce screen 1:
0. Change the language to Chinese in the system settings
1. Install alwayson and open
2. Click on "Customize Watchface" ("自定义时钟样式" in chinese)

Steps to reproduce screen 2:
0. Change the language to Chinese in the system settings
1. Install alwayson and open
2. Click on "Brightness" ("亮度" in chinese)

Steps to reproduce screen 3:
0. Change the language to Chinese in the system settings
1. Install alwayson and open
2. Click on "Notifications" ("通知" in chinese)

Steps to reproduce screen 4:
0. Change the language to Chinese in the system settings
1. Install alwayson and open
2. Click on "Gestures & shortcuts" ("手势与快捷方式" in chinese)
3. Click on "Double tap action" ("双击操作" in chinese)

Steps to reproduce screen 5:
01. Change the language to Chinese in the system settings
1. Install alwayson and open
2. Scroll backward

**Expected behavior**
The text is translated correctly

**Screenshots**
screen 1:
<img src="https://user-images.githubusercontent.com/15941953/90335977-411e7a80-e00b-11ea-8b8d-3f310be8fb9d.png" width="270" height="600"/>
screen 2:
<img src="https://user-images.githubusercontent.com/15941953/90336033-b427f100-e00b-11ea-884a-a980b78d3095.png" width="270" height="600"/>
screen 3:
<img src="https://user-images.githubusercontent.com/15941953/90336080-023cf480-e00c-11ea-8319-3ec538e44a28.png" width="270" height="600"/>
screen 4:
<img src="https://user-images.githubusercontent.com/15941953/90336126-492aea00-e00c-11ea-8e24-0231b52dda6d.png" width="270" height="600"/>
screen 5:
<img src="https://user-images.githubusercontent.com/15941953/90336234-f00f8600-e00c-11ea-915b-0bb22bf7014f.png" width="270" height="600"/>

**Comment by rosenpin** [comment]
You can help translating the app here https://crowdin.com/project/always-on-amoled

**Comment by sjl872964789** [comment]
Thanks for your quick confirmation and reply. I will continue to check other pontential translation errors and update the info here, and later integrate them into the app when I have more time (or someone else is willing offer the help).

**Comment by rosenpin** [comment]
Translations for this app are provided by and for the community, causing them to be partial. Can't fix
