### ISSUE TITLE
Language settings are not persistent

### ISSUE THREAD

**Issue by sjl872964789** [rosenpin/always-on-amoled#2476]
**Describe the bug**
After I changed the language setting of the system (to Chinese), I closed and re-entered Alwayson, the language setting changed back to English

**Context**
 - Device: [Galaxy A6s]
 - OS version: [Android 7.1.2]
 - App version: [1.6.2]

**How to reproduce**
Steps to reproduce screen 1:
1. Install alwayson and open
2. Change the language to Chinese in the system settings
3. Back to alwayson
4. At this time alwayson is Chinese
5. Clear alwayson from the background
6. Reopen alwayson
7. Alwayson has changed back to English

**Expected behavior**
Alwayson's language is consistent with the language set by the system setting

**Screenshots**
![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/15941953/90337199-86df4100-e013-11ea-9f91-5476c7324bf2.gif)

**Comment by rosenpin** [comment]
You can change the app language inside the app, go to advanced settings, and set the language to Chinese

**Comment by rosenpin** [comment]
removed independent language chooser
