### ISSUE TITLE
Add automatic rule for airplane mode

### ISSUE THREAD

**Issue by CombeeMike** [rosenpin/always-on-amoled#2494]
I'd really appreciate a new option within `Automatic Rules` to disable the service when device is in airplane mode. I use to put my phone in airplane mode over night and having this option would be more "accurate" then setting some fixed "disabled time"...

I could also do this with #2495. Having one of those 2 would be enough for me. Whichever makes more sense to you and/or is easier to implement 🤷‍♂️

**Comment by rosenpin** [comment]
Guess since it can now be done using tasker, there's no need to implement it specifically for airplane mode
