### ISSUE TITLE
Allow permanent disabling of service via Tasker

### ISSUE THREAD

**Issue by CombeeMike** [rosenpin/always-on-amoled#2495]
Running the `Stop always on` option of the Tasker integration seems to be a "one time shot" kind of thing which only disables the currently shown instance of the app but doesn't disable the service for future "wake calls" (new notifications in my case).

Could you add some option to permanently stop/start the service via Tasker which could be used in addition to the `Automatic rules` inside the app?

I'd use this to completely disable `Always On AMOLED` when in airplane mode so it's directly related to #2494. Having one of those 2 would be enough for me. Whichever makes more sense to you and/or is easier to implement 🤷‍♂️

**Comment by rosenpin** [comment]
Great suggestion, I'll add it when I get a chance

**Comment by rosenpin** [comment]
I added this option, it will be available whenever the next version of the app will be released (1.7.4)

**Comment by CombeeMike** [comment]
😲
Thank you very much for implementing this so fast!
I'm really looking forward to this!

**Comment by rosenpin** [comment]
Sure thing, it's already available in the open beta
