### ISSUE TITLE
Color in the APP

### ISSUE THREAD

**Issue by Goliath0** [rosenpin/always-on-amoled#2507]
In the App the spwxial color is violet and bad to read in dark modus of the device. How can I change it?

It's nead a manuel or wiki how to deal with the App and what provides all the features. How to set the system flags like the system AOD of Samsung and other wiki or FAQ Question of a Dau.

An explanarion of the chronology of process of locking the screen and change to the AOD and then change to black screen. What duration for what process?

It don't work with me. I will open a new issue for that.

**Comment by rosenpin** [comment]
I made several big changes to the app which I believe should have addressed this concern, can you confirm?

**Comment by rosenpin** [comment]
Closing this due to the app having many changes and fixes since. If this issue persist let me know

**Comment by Goliath0** [comment]
I don’t use this AP anymore, if SAMSUNG has his own AOD. So I cannot say if it is fixed. SM-J500FN

 

Von: Tomer Rosenfeld ***@***.*** 
Gesendet: Dienstag, 26. September 2023 12:42
An: rosenpin/always-on-amoled
Cc: Goliath0; Author
Betreff: Re: [rosenpin/always-on-amoled] Color in the APP (#2507)

 

Closing this due to the app having many changes and fixes since. If this issue persist let me know
