### ISSUE TITLE
Samsung Galaxi J500nf Lineage OS don't work property

### ISSUE THREAD

**Issue by Goliath0** [rosenpin/always-on-amoled#2508]
Installed with root and plugin for Hardware keys. The AOD function of the Android is on (active). Duration of swich off the screen is 5 minutes. If I put the power button, the lock screen is showing with notes and clock. Short flash on the new AOA screen before this. AOA Screen is no more visible. After 5 minutes, the screnn goes to black or to the system AOD Screen. What goes wrong here?

If I wipe the lockscreen to bottom, your AOD Screen flashes on for 0,15 second and than the screen ist unlocked normaly.

Have installed Magisk, AdAway, AFwall+. Google Play services are running well. Need the APP some datatransfer via WiFi to some servers or LTE? And which URLs?

Android 10.

Need help
David

**Comment by Goliath0** [comment]
A hint for the problem investigation. In some Samsung divices the original AOD is closed if the power safing mode is on and the power is below ca. 70 %. If the power cable is in the issue lost. This is an intern Samsung feature. Possible this has consequences for AOA also?

**Comment by rosenpin** [comment]
I believe this should have been fixed, if you still use the app can you confirm?

**Comment by rosenpin** [comment]
Closing this due to the app having many changes and fixes since. If this issue persist let me know
