### ISSUE TITLE
The Default Lock Screen Appears after AOA Screen

### ISSUE THREAD

**Issue by iasad12** [rosenpin/always-on-amoled#2509]
Greetings, 

I don't know whether this is a bug or a feature, the default lock screen of One UI 2 appears after the timeout of the Always on AMOLED runs out. 

I just want my default lock screen to appear when I intend to. Is there a way to turn this behaviour off? I just want only AOA screen. 

Thanks!

**Comment by rosenpin** [comment]
This is definitely a bug 

Related 
https://github.com/rosenpin/always-on-amoled/issues/2447

**Comment by iasad12** [comment]
Greetings, 

I just had to give the app the permission to Change System Settings and the issue or bug has been resolved. 

Device name: Samsung Galaxy J4 2018
Android version: One UI 2 - Android 10
