### ISSUE TITLE
Enhancement suggestions

### ISSUE THREAD

**Issue by Conn79** [rosenpin/always-on-amoled#2514]
Hi, just wanted to let you know, this is the best app I found so far :)

Just a few ideas to enhance the app.

1)
What I find disturbing is the pop-up when swiping the status bar down which says "AOA is active". Could you disable this please? I think it is sufficient enough if the AOA letters are displayed in the notch bar

![Image2](https://user-images.githubusercontent.com/9334021/202901367-626f2879-e40f-41b6-88cb-f661e851e0bb.jpg)

2)
When charging the battery it says "AC charge, xx minutes to full". This is georgeous, but may I suggest to leave the AC charge away, I'd guess nobody charges with DC. Also it would be nicer to give a colored battery symbol, red:0-70%, orange:80-99% and green 100% there too.

3)
would it be possible to give the notifications a color, like green for whatsapp, blue for signal, or something like thisß

**Comment by rosenpin** [comment]
This is not the correct app  
I'm not sure what app you are using but this repo is associated to this app  
https://play.google.com/store/apps/details?id=com.tomer.alwayson
