### ISSUE TITLE
[BUG] Source code is missing

### ISSUE THREAD

**Issue by pallaswept** [rosenpin/always-on-amoled#2554]
**Describe the bug**
Title

**Expected behavior**
Find source code here

**Comment by rosenpin** [comment]
See here: https://github.com/rosenpin/always-on-amoled/issues/2406#issuecomment-569726156

**Comment by pallaswept** [comment]
OK thanks. Such a shame, I downloaded it from f-droid but I'll have them remove it.

**Comment by rosenpin** [comment]
The F-Droid version was compiled from the open source code. The code is no longer officially available but can be obtained by browsing forks of this repo from before 02/23/2017
